---
- name: Install required packages
  loop: "{{ ['etcd'] if ansible_distribution_version is version('24.04', '<') else ['etcd-server', 'etcd-client'] }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - etcd

- name: Write profile script
  ansible.builtin.template:
    src: profile.j2
    dest: /etc/profile.d/etcdctl.sh
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - etcd

- name: Create pki dir
  ansible.builtin.file:
    path: /etc/etcd/pki
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - etcd

- name: Write peer CA
  notify:
    - Restart etcd
  ansible.builtin.copy:
    content: "{{ etcd_peer_ca_cert }}"
    dest: /etc/etcd/pki/peer-ca.crt
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Check peer cert
  ansible.builtin.stat:
    path: /etc/etcd/pki/peer.crt
  register: peer_cert_result
  tags:
    - etcd

- name: Peer CA json
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  ansible.builtin.copy:
    content: "{{ etcd_peer_ca_config | to_json }}"
    dest: /etc/etcd/pki/ca.json
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Peer CA key
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  ansible.builtin.copy:
    content: "{{ etcd_peer_ca_key }}"
    dest: /etc/etcd/pki/ca.key
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Peer cert json
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  ansible.builtin.copy:
    content: "{{ etcd_peer_config | to_json }}"
    dest: /etc/etcd/pki/peer.json
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Generate peer cert
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  register: generated_peer_cert
  changed_when: false
  failed_when: generated_peer_cert.rc != 0
  ansible.builtin.command: cfssl gencert -config=/etc/etcd/pki/ca.json -ca=/etc/etcd/pki/peer-ca.crt -ca-key=/etc/etcd/pki/ca.key /etc/etcd/pki/peer.json
  tags:
    - etcd

- name: Parse peer cert
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  ansible.builtin.set_fact:
    etcd_generated_peer_cert: "{{ generated_peer_cert.stdout | from_json }}"
  tags:
    - etcd

- name: Write peer cert
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  notify:
    - Restart etcd
  ansible.builtin.copy:
    content: "{{ etcd_generated_peer_cert.cert }}"
    dest: /etc/etcd/pki/peer.crt
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Write peer key
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  notify:
    - Restart etcd
  ansible.builtin.copy:
    content: "{{ etcd_generated_peer_cert.key }}"
    dest: /etc/etcd/pki/peer.key
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Delete peer artifacts
  when:
    - (peer_cert_result.stat is defined and not peer_cert_result.stat.exists) or etcd_peer_cert_overwrite
  loop:
    - /etc/etcd/pki/ca.json
    - /etc/etcd/pki/ca.key
    - /etc/etcd/pki/peer.json
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  tags:
    - etcd

- name: Write client CA
  notify:
    - Restart etcd
  ansible.builtin.copy:
    content: "{{ etcd_client_ca_cert }}"
    dest: /etc/etcd/pki/client-ca.crt
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Check client cert
  ansible.builtin.stat:
    path: /etc/etcd/pki/client.crt
  register: client_cert_result
  tags:
    - etcd

- name: Client CA json
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  ansible.builtin.copy:
    content: "{{ etcd_client_ca_config | to_json }}"
    dest: /etc/etcd/pki/ca.json
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Client CA key
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  ansible.builtin.copy:
    content: "{{ etcd_client_ca_key }}"
    dest: /etc/etcd/pki/ca.key
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Client cert json
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  ansible.builtin.copy:
    content: "{{ etcd_client_config | to_json }}"
    dest: /etc/etcd/pki/client.json
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Generate client cert
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  register: generated_client_cert
  changed_when: false
  failed_when: generated_client_cert.rc != 0
  ansible.builtin.command: cfssl gencert -config=/etc/etcd/pki/ca.json -ca=/etc/etcd/pki/client-ca.crt -ca-key=/etc/etcd/pki/ca.key /etc/etcd/pki/client.json
  tags:
    - etcd

- name: Parse client cert
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  ansible.builtin.set_fact:
    etcd_generated_client_cert: "{{ generated_client_cert.stdout | from_json }}"
  tags:
    - etcd

- name: Write client cert
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  notify:
    - Restart etcd
  ansible.builtin.copy:
    content: "{{ etcd_generated_client_cert.cert }}"
    dest: /etc/etcd/pki/client.crt
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Write client key
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  notify:
    - Restart etcd
  ansible.builtin.copy:
    content: "{{ etcd_generated_client_cert.key }}"
    dest: /etc/etcd/pki/client.key
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - etcd

- name: Delete client artifacts
  when:
    - (client_cert_result.stat is defined and not client_cert_result.stat.exists) or etcd_client_cert_overwrite
  loop:
    - /etc/etcd/pki/ca.json
    - /etc/etcd/pki/ca.key
    - /etc/etcd/pki/client.json
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  tags:
    - etcd

- name: Write env config
  notify:
    - Restart etcd
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/etcd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - etcd

- name: Write service file
  notify:
    - Restart etcd
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - etcd

- name: Start etcd service
  ansible.builtin.systemd:
    name: etcd
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - etcd

...
